### ISSUE TITLE
Usage questions

### ISSUE THREAD

**Issue by kazazor** [lstn/misc-grafana-dashboards#12]
Hi, I couldn't add a "Question" label - but that's the intent of this issue:
1. This dashboard uses postgress-exporter, does it need to be installed on the same machine where my Postgres database is? Or will it work if installed on a different machine and just provide the DB connection details?

I'm asking that mainly for the CPU & Memory usage metrics.. For some reason I see my DB has very low RAM usage, seems wayyy too low IMO (FYI, I installed PG using docker on a k8s pod and postgres-exporter on another pod using docker).
<img width="454" alt="Screen Shot 2022-01-22 at 21 25 39" src="https://user-images.githubusercontent.com/1577655/150652823-1e1d8314-7d93-427e-b211-ab3cd1e78102.png">

2. How can I understand the metrics around CPU time? Usually, you see CPU usage as a percentage, but here it's CPU time. How can one tell if it's low/mid/high? Maybe you can help transfer it to percentage instead of CPU time?

3. Does it report also the storage of the DB? Meaning how much storage the DB is using. And even better, how much storage it has left on the machine..

4. I see also the "Start Time" is always NA for me.
<img width="228" alt="Screen Shot 2022-01-22 at 21 29 16" src="https://user-images.githubusercontent.com/1577655/150652908-3907b6f2-7330-4c25-b0ee-6cb7d8d8107f.png">

Is that a problem on my end? Or in the dashboard?

5. More of a pg-exporter question, but any special instructions on how to create the readonly user so everything will work? I did it this way: https://github.com/prometheus-community/postgres_exporter#running-as-non-superuser

Did I miss anything?

Thank you very much!

**Comment by Radiergummi** [comment]
@kazazor start time is also N/A for me, and as far as I can see, the related metric `pg_postmaster_start_time_seconds` is not even collected by postgres_exporter... Did you find a solution?
